import jsPDF from 'jspdf'

export async function exportNoteToPDF(notebook) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  })

  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 20
  const contentWidth = pageWidth - (margin * 2)
  let yPos = margin

  // Colors
  const primaryColor = [66, 133, 244] // Google Blue
  const secondaryColor = [52, 168, 83] // Google Green
  const textColor = [32, 33, 36]
  const mutedColor = [95, 99, 104]

  // Helper function to add new page if needed
  const checkNewPage = (neededHeight = 20) => {
    if (yPos + neededHeight > pageHeight - margin) {
      doc.addPage()
      yPos = margin
      addHeader()
      return true
    }
    return false
  }

  // Add header with PRISM branding
  const addHeader = () => {
    // Logo area - gradient effect simulation
    doc.setFillColor(...primaryColor)
    doc.roundedRect(margin, yPos, 12, 12, 3, 3, 'F')
    
    // PRISM text
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(18)
    doc.setTextColor(...primaryColor)
    doc.text('PRISM', margin + 16, yPos + 9)

    // Tagline
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...mutedColor)
    doc.text('Learn from First Principles', margin + 16, yPos + 14)

    // Date on right
    doc.setFontSize(9)
    doc.text(new Date().toLocaleDateString('en-IN', { 
      day: 'numeric', 
      month: 'long', 
      year: 'numeric' 
    }), pageWidth - margin, yPos + 9, { align: 'right' })

    yPos += 25

    // Divider line
    doc.setDrawColor(...primaryColor)
    doc.setLineWidth(0.5)
    doc.line(margin, yPos, pageWidth - margin, yPos)
    yPos += 10
  }

  // Add footer
  const addFooter = (pageNum, totalPages) => {
    const footerY = pageHeight - 10
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...mutedColor)
    doc.text(`Generated by PRISM - prism.app`, margin, footerY)
    doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - margin, footerY, { align: 'right' })
  }

  // Start building PDF
  addHeader()

  // Notebook Title
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.setTextColor(...textColor)
  const titleLines = doc.splitTextToSize(notebook.topic_title || 'Untitled Notebook', contentWidth)
  doc.text(titleLines, margin, yPos)
  yPos += (titleLines.length * 9) + 5

  // Subtitle
  doc.setFont('helvetica', 'italic')
  doc.setFontSize(10)
  doc.setTextColor(...mutedColor)
  doc.text('AI-Generated Learning Notes', margin, yPos)
  yPos += 15

  // Content parsing and rendering
  const content = notebook.content || 'No content available'
  const lines = content.split('\n')

  for (const line of lines) {
    const trimmedLine = line.trim()
    
    if (!trimmedLine) {
      yPos += 4
      continue
    }

    checkNewPage()

    // Headers
    if (trimmedLine.startsWith('### ')) {
      yPos += 5
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(13)
      doc.setTextColor(...secondaryColor)
      const headerText = trimmedLine.replace('### ', '').replace(/[^\w\s-]/g, '').trim()
      const headerLines = doc.splitTextToSize(headerText, contentWidth)
      doc.text(headerLines, margin, yPos)
      yPos += (headerLines.length * 6) + 4
    }
    else if (trimmedLine.startsWith('## ')) {
      yPos += 6
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(15)
      doc.setTextColor(...primaryColor)
      const headerText = trimmedLine.replace('## ', '').replace(/[^\w\s-]/g, '').trim()
      const headerLines = doc.splitTextToSize(headerText, contentWidth)
      doc.text(headerLines, margin, yPos)
      yPos += (headerLines.length * 7) + 5
    }
    else if (trimmedLine.startsWith('# ')) {
      yPos += 8
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(18)
      doc.setTextColor(...textColor)
      const headerText = trimmedLine.replace('# ', '').replace(/[^\w\s-]/g, '').trim()
      const headerLines = doc.splitTextToSize(headerText, contentWidth)
      doc.text(headerLines, margin, yPos)
      yPos += (headerLines.length * 8) + 6
    }
    // Bullet points
    else if (trimmedLine.startsWith('- ') || trimmedLine.startsWith('* ')) {
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(11)
      doc.setTextColor(...textColor)
      
      // Bullet
      doc.setFillColor(...primaryColor)
      doc.circle(margin + 2, yPos - 1.5, 1, 'F')
      
      // Text (remove markdown bold markers)
      const bulletText = trimmedLine.substring(2).replace(/\*\*/g, '').replace(/\*/g, '')
      const bulletLines = doc.splitTextToSize(bulletText, contentWidth - 10)
      doc.text(bulletLines, margin + 8, yPos)
      yPos += (bulletLines.length * 5) + 2
    }
    // Regular text
    else {
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(11)
      doc.setTextColor(...textColor)
      
      // Clean up markdown formatting
      const cleanText = trimmedLine
        .replace(/\*\*/g, '')
        .replace(/\*/g, '')
        .replace(/`/g, '')
        .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
      
      const textLines = doc.splitTextToSize(cleanText, contentWidth)
      
      for (const textLine of textLines) {
        checkNewPage()
        doc.text(textLine, margin, yPos)
        yPos += 5
      }
      yPos += 2
    }
  }

  // Add footers to all pages
  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    addFooter(i, totalPages)
  }

  // Add final branding page
  doc.addPage()
  const centerX = pageWidth / 2
  const centerY = pageHeight / 2

  // Large PRISM logo
  doc.setFillColor(...primaryColor)
  doc.roundedRect(centerX - 15, centerY - 40, 30, 30, 6, 6, 'F')
  
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(32)
  doc.setTextColor(...primaryColor)
  doc.text('PRISM', centerX, centerY + 10, { align: 'center' })

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(14)
  doc.setTextColor(...mutedColor)
  doc.text('Learn from First Principles', centerX, centerY + 22, { align: 'center' })

  doc.setFontSize(11)
  doc.text('Powered by Google Gemini AI', centerX, centerY + 35, { align: 'center' })

  doc.setFontSize(10)
  doc.setTextColor(...primaryColor)
  doc.text('prism.app', centerX, centerY + 50, { align: 'center' })

  addFooter(totalPages + 1, totalPages + 1)

  // Generate filename
  const sanitizedTitle = (notebook.topic_title || 'notebook')
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .replace(/\s+/g, '-')
    .toLowerCase()
    .substring(0, 30)
  
  const filename = `prism-${sanitizedTitle}-${Date.now()}.pdf`

  // Save the PDF
  doc.save(filename)
  
  return filename
}
